name: Deploy to AWS ECSv2
on:
  push:
    branches: [dev]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup JAVA 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build docker image
        run: docker build -t napadovskibohdan/grandpa-weather .
      - name: Publish image to docker hub
        run: docker push napadovskibohdan/grandpa-weather:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull napadovskibohdan/grandpa-weather:latest
      - name: Delete old container
        run: docker rm -f grandpa-weather-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name grandpa-weather-container napadovskibohdan/grandpa-weather